### ISSUE TITLE
SqlSerDsc Issue : PowerShell DSC resource MSFT_SqlSetup failed to execute Set-TargetResource functionality with error message

### ISSUE THREAD

**Issue by baba-dude** [dsccommunity/SqlServerDsc#1273]
I am Trying to Install SqlServer on windows from ansible. Unfortunately i am stuck at this error.

PowerShell DSC resource MSFT_SqlSetup failed to execute Set-TargetResource functionality with error message:System.Exception: Test-TargetResource returned false after calling Set-TargetResource.

Can you Please suggest me why i am getting these kind of error.

My Playbook paraeters are as below.
```
- name: Install SQL Server
  win_dsc:
    resource_name: SQLSetup
    Action: Install
    UpdateEnabled: True
    SourcePath: C:\SQLInstall\SQLServer2017-DEV-x64-ENU
    InstanceName: "{{ mssql_instance_name }}"
    InstallSharedDir: "{{ mssql_installshared_path }}"
    InstallSharedwowDir: "{{ mssql_installsharedwow_path }}"
    InstanceDir: "{{ mssql_instance_path }}"
    InstallSQLDataDir: "{{ mssql_sqlinstalldata_path }}"
    SQLUserDBDir: "{{ mssql_sqluserdata_path }}"
    SQLUserDBLogDir: "{{ mssql_sqluserlog_path }}"
    SQLTempDBDir: "{{ mssql_sqltempDB_path }}"
    SQLTempDBLogDir: "{{ mssql_sqltempDBlog_path }}"
    Features: "{{ mssql_features }}"
    SQLCollation: "{{ mssql_collation }}"
    BrowserSvcStartupType: "{{ mssql_browsersvc_mode }}"
    SuppressReboot: "{{ mssql_suppress_reboot }}"
    # SQL Service Account
    SQLSvcAccount_username: NT Service\SQLSERVERAGENT
    SQLSvcAccount_password: Password@123
    # SQL Agent Service Account
    AgtSvcAccount_username: NT Service\SQLSERVERAGENT
    AgtSvcAccount_password: Password@123
    # SQL Analysis Services Account
    ASSvcAccount_username: NT Service\SQLSERVERAGENT
    ASSvcAccount_password: Password@123
    # Used when installing on a network path, comment out
    # SourceCredential_username: "{{ ansible_user }}"
    # SourceCredential_password: "{{ ansible_password }}"

    # System Admins
    SQLSysAdminAccounts: win1\baba
    # Analysis Services Admins (if installed)
    ASSysAdminAccounts: win1\baba
  tags: install_sql
```

Please advise..:
