### ISSUE TITLE
SqlServerDsc: GitVersion used in pipeline wrongly configured

### ISSUE THREAD

**Issue by johlju** [dsccommunity/SqlServerDsc#1674]
The component `gitversion` that is used in the pipeline was wrongly configured when the repository moved to the new default branch `main`. It throws and error when using newer versions of GitVersion.

```
ERROR [01/16/21 13:31:41:37] An unexpected error occurred:
GitVersion.Configuration.ConfigurationException: Branch configuration 'feature' defines these 'source-branches' that are not configured: '[main]'
```

The part of GitVersion.yml:

```
  feature:
    tag: useBranchName
    increment: Minor
    regex: f(eature(s)?)?[\/-]
    source-branches: ['main']
  hotfix:
    tag: fix
    increment: Patch
    regex: (hot)?fix(es)?[\/-]
    source-branches: ['main']
```

must be changed to 

```
  feature:
    tag: useBranchName
    increment: Minor
    regex: f(eature(s)?)?[\/-]
    source-branches: ['master']
  hotfix:
    tag: fix
    increment: Patch
    regex: (hot)?fix(es)?[\/-]
    source-branches: ['master']
```

This is due to that the key `master` is hard-coded into GitVersions configuration file, and the key `source-branches:` must refer to a branch listed under the key `branches:` (which is in this case the hard-coded key `master:`).
